//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.EFDesignLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public string CurrencyCode { get; set; }
        public System.DateTime DateBegin { get; set; }
        public decimal RateValue { get; set; }
    }
}
