//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.EFDesignLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICDBContext : DbContext
    {
        public ICDBContext()
            : base("name=ICDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advertising> Advertising { get; set; }
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<CurrencyRate> CurrencyRate { get; set; }
        public virtual DbSet<SystemTranslation> SystemTranslation { get; set; }
        public virtual DbSet<ContentTranslation> ContentTranslation { get; set; }
        public virtual DbSet<EventLog> EventLog { get; set; }
        public virtual DbSet<ProductAction> ProductAction { get; set; }
        public virtual DbSet<ProductLog> ProductLog { get; set; }
        public virtual DbSet<StoreAdvertising> StoreAdvertising { get; set; }
        public virtual DbSet<ProductPrice> ProductPrice { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<RetailAction> RetailAction { get; set; }
        public virtual DbSet<StoreAction> StoreAction { get; set; }
        public virtual DbSet<TerminalLanguage> TerminalLanguage { get; set; }
        public virtual DbSet<TerminalCurrency> TerminalCurrency { get; set; }
    }
}
