//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.EFDesignLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string BarcodeValue { get; set; }
        public byte ActivityStatus { get; set; }
        public string Article { get; set; }
        public int CaptionID { get; set; }
        public int DescriptionID { get; set; }
        public byte[] Image { get; set; }
    }
}
