//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.Server.DataLayerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigID { get; set; }
        public string StoreID { get; set; }
        public string TerminalID { get; set; }
        public string ConfigValue { get; set; }
    }
}
