//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.Server.DataLayerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public string CurrencyCode { get; set; }
        public int CaptionID { get; set; }
        public byte[] Image { get; set; }
    }
}
