//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC.Server.DataLayerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public string TerminalID { get; set; }
        public string StoreID { get; set; }
        public string MacAddress { get; set; }
        public string IPAddress { get; set; }
        public byte ActivityStatus { get; set; }
        public string TerminalUID { get; set; }
        public string TerminalVersion { get; set; }
    }
}
